---
name: weave-scope
releases:
- name: weave-scope
  version: latest
stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest
instance_groups:
- name: scope_app
  azs:
  - ap-northeast-1a
  instances: 1
  jobs:
  - name: scope_app
    release: weave-scope
    consumes: {}
    provides:
      weave_scope_app:
        as: weave_scope_app
        shared: true
  vm_type: t3.medium
  stemcell: default
  properties: {}
  update:
    serial: true
    max_in_flight: 1
  networks:
  - default:
    - dns
    - gateway
    name: tas-pcf-subnet-1
  persistent_disk_type: '10240'
  vm_extensions: [vm-extensiona-weavo]
update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 1
  max_errors: 2
  serial: true
