---
releases:
- name: weave-scope
  version: 0.0.17

addons:
- name: scope-probe
  jobs:
  - name: scope_probe
    release: weave-scope
    consumes:
      weave_scope_app:
        from: weave_scope_app
        deployment: weave-scope
- name: scope-garden
  include:
    jobs:
    - name: garden
      release: garden-runc
  jobs:
  - name: scope_garden
    release: weave-scope
    properties:
      weave:
        scope:
          probe:
            garden:
              addr: /var/vcap/data/garden/garden.sock
            cf:
              api_url: https://api.sys.leedh.cloud
              client_id: scope-admin
              client_secret: scope-admin
              skip_ssl_verify: true
